####
#Classpath and file-based solution
####
server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          #search-locations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice
          search-locations: classpath:config/,classpath:config/licensingservice, classpath:config/organizationservice
